#!/usr/bin/env bash

# link in txt/*txt files need for study description
# link in data for BOLD/task* and anatomy
# writes demographic.txt


openfmridir=".."
study="ringrewad"
[ ! -d $openfmridir ]  && mkdir $openfmridir

# input from demographic file generated by 00_getDemographics.bash
# looks like
#    sub001	10133	20070131	ANTI	9.7960	F	070131164507	2007-01-31 00:00:00	1997-04-15 00:00:00
while read subjid lunaid visit task age sex birc rest; do
  echo "${lunaid}_${visit}"
  #mkdir -p $openfmridir/$subjid/{anatomy,{behave,BOLD}/}
done < txt/demographicsFromSQL.txt 
